# https://github.com/release-drafter/release-drafter?tab=readme-ov-file#configuration-options
template: |
  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...$RESOLVED_VERSION
name-template: 'docs-builder $RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
change-template: '- $TITLE by @$AUTHOR in #$NUMBER'
categories:
  - title: '💥 Breaking Changes'
    labels:
      - 'breaking' # When a breaking change is introduced
  - title: '✨ Features'
    labels:
      - 'feature' # When a new feature is introduced
      - 'enhancement' # When an existing feature is improved
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug' # When a bug is fixed
      - 'fix' # When a bug is fixed
  - title: '📝 Documentation'
    labels:
      - 'documentation' # When documentation is updated
  - title: '🧰 Maintenance'
    labels:
      - 'chore' # When a chore is done
      - 'dependencies' # When dependencies are updated
  - title: '⚙️ Automation'
    labels:
      - 'automation' # When automation is updated
      - 'ci' # When automation is updated
  - title: '🎨 Redesign' # Temporary category while we're redesigning the docs
    labels:
      - 'redesign' # When it's a redesign feature
exclude-labels:
  - 'changelog:skip' # When a PR should be excluded from the changelog
version-resolver:
  major:
    labels:
      - 'breaking'
  minor:
    labels:
      - 'feature'
      - 'enhancement'
  default: patch
