name: 'Documentation Builder'
description: 'Build and validate documentation in your repository'

branding:
  icon: 'filter'
  color: 'red'

inputs:
  prefix:
    description: 'Path prefix for all urls'
    required: false
  strict:
    description: 'Treat warnings as errors'
    required: false

runs:
  using: 'docker'
  image: "docker://ghcr.io/elastic/docs-builder:edge"
