name: Feature Request
description: Suggest an idea for improving docs-builder.
title: "[Feature Request]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest an improvement to docs-builder! Please fill out this form as completely as possible.

  - type: checkboxes
    attributes:
      label: Prerequisites
      description: Please verify you have completed the following
      options:
        - label: I have searched existing issues to ensure this feature hasn't already been requested
          required: true
        - label: I have tested using the latest version of docs-builder
          required: true

  - type: textarea
    id: problem
    attributes:
      label: What problem are you trying to solve?
      description: |
        Describe the context and limitation you're encountering. Remember that it might not be obvious to others why this is important!
      placeholder: |
        Example: When building documentation for my project, I often need to update the revision date at the top of each file. Currently, I have to manually edit each file, which is time-consuming and error-prone.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: |
        Describe your proposed solution. Include as much detail as you can, but remember that there might be other solutions we haven't thought of!
      placeholder: |
        Example: Add a CLI flag --auto-update-revision-date that automatically updates a specified metadata field in all documentation files when building.
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Examples and Research
      description: |
        Please provide any relevant examples, research, or references that support this feature request:
        - Similar features in other documentation tools
        - Code samples showing how you'd use this feature
        - Links to relevant standards or conventions
        - Screenshots or diagrams of your proposed solution
      placeholder: |
        - MkDocs has a similar feature using their `git-revision-date-localized` plugin
        - Jekyll's `last_modified_at` plugin demonstrates this functionality
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: |
        What alternative solutions have you considered or tried? Why aren't they sufficient?
      placeholder: |
        I've tried using git hooks to update the dates, but this doesn't work well in CI/CD pipelines.
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the feature request here.
      placeholder: |
        - This would be particularly useful for compliance documentation where revision dates are mandatory
        - Could potentially integrate with git history for more accurate dating
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: How important is this feature to you?
      options:
        - Nice to have
        - Important
        - Critical
    validations:
      required: true
