name: preview-deploy

on:
  workflow_call: ~
  workflow_run:
    workflows: [preview-build]
    types:
      - completed

permissions:
  contents: none
  id-token: write
  deployments: write
  actions: read

jobs:
  do-nothing:
    runs-on: ubuntu-latest
    steps:
      - name: Do nothing
        run: echo "This is here for backwards compatibility. After validating that the preview-build workflow is working as expected, you can remove this workflow file."
